// <auto-generated />
namespace Aula_01___MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class TreinEcola : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TreinEcola));
        
        string IMigrationMetadata.Id
        {
            get { return "202004041414240_TreinEcola"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
